#!/usr/bin/env python3
"""Terminal entry point: one question in, a cited answer out.

This is the debugging tool the spec calls for, and it is deliberately more verbose
than the UI. It shows the same `Answer` the UI renders, plus the retrieved chunks
behind it, because "the answer was wrong" is almost always either a retrieval miss
or a chunk that does not contain what the question asked for — and you cannot tell
which from the answer alone.

Usage:
    python cli.py "What is the exit load on HDFC Large Cap?"
    python cli.py "What is the exit load on HDFC Large Cap?" --sources
    python cli.py --sample          # write reports/sample_qa.md
    python cli.py --sample --force   # re-generate, spending tokens
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

import config  # noqa: E402
from rag.pipeline import answer  # noqa: E402
from rag.verifier import ANSWERED  # noqa: E402

#: The six acceptance questions plus the refusals, for the sample Q&A file.
#: Chosen to show every status a user will actually hit, not to flatter the system.
SAMPLE_QUESTIONS = [
    "What is the expense ratio of HDFC Large Cap Fund?",
    "What is the exit load on HDFC Small Cap Fund?",
    "What is the minimum SIP amount for HDFC Balanced Advantage Fund?",
    "What is the lock-in period for HDFC ELSS Tax Saver Fund?",
    "What is the riskometer level and benchmark of HDFC Equity Fund?",
    "What is the expense ratio of HDFC Flexi Cap Fund?",
    "Should I buy HDFC Small Cap Fund?",
    "What is the CAGR of HDFC Large Cap Fund?",
    "What is the expense ratio of Parag Parikh Flexi Cap Fund?",
    "My PAN is ABCDE1234F",
    "What is the boiling point of water at sea level?",
]


def _wrap(text: str, width: int = 88, indent: str = "") -> str:
    import textwrap

    return "\n".join(textwrap.wrap(text, width=width, initial_indent=indent,
                                   subsequent_indent=indent))


def render_answer(result, show_sources: bool = False) -> str:
    lines = []
    lines.append(f"\nQ: {result.query}")
    lines.append(f"status: {result.status}")
    lines.append("")
    lines.append(_wrap(result.answer))
    lines.append("")

    if result.citation_url:
        lines.append(f"Source: {result.citation_url}")

    # PRD acceptance criterion 6 asks for this exact wording, and it is shown for
    # every answer that has evidence behind it. A refusal has no evidence and
    # nothing to date, so it says so rather than printing an empty label.
    if result.last_updated:
        lines.append(f"Last updated from sources: {result.last_updated}")
    else:
        lines.append("Last updated from sources: n/a (no source retrieved)")

    if result.status == ANSWERED and not result.citation_url:
        lines.append("WARNING: answered with no citation")

    if show_sources and result.evidence:
        lines.append("")
        lines.append("Sources retrieved:")
        for hit in result.evidence:
            lines.append(
                f"  [{hit.score:.4f}] {hit.chunk.scheme} | {hit.chunk.section}"
            )
            lines.append(f"      {hit.chunk.source_url}")
            lines.append(_wrap(hit.chunk.text, width=84, indent="      "))
            lines.append("")

    lines.append("")
    lines.append(f"({config.disclaimer_text()})")
    return "\n".join(lines)


def _sample_md(results) -> str:
    lines = [
        "# Sample Q&A",
        "",
        "Facts-only assistant for HDFC mutual fund schemes. Generated by "
        "`python cli.py --sample`.",
        "",
        f"> {config.disclaimer_text()}",
        "",
        "Every answer below is real output from the pipeline, not hand-written. Refusals",
        "are included on purpose: a demo that only shows the happy path is not evidence",
        "of anything.",
        "",
    ]
    for result in results:
        lines.append(f"### {result.query}")
        lines.append("")
        lines.append(f"**Status:** `{result.status}`")
        lines.append("")
        lines.append(f"> {result.answer}")
        lines.append("")
        if result.citation_url:
            lines.append(f"**Source:** {result.citation_url}")
            lines.append("")
        if result.last_updated:
            lines.append(f"**Last updated from sources:** {result.last_updated}")
            lines.append("")
    return "\n".join(lines)


def _preflight() -> bool:
    """Fail before spending a token, not after."""
    problems = []
    if not config.CHROMA_DIR.exists():
        problems.append(f"no index at {config.CHROMA_DIR} — run: python run_ingest.py --index")
    if config.LLM_BACKEND == "groq" and not Path(
        str(config.BASE_DIR / "docs" / ".env")
    ).exists() and not Path(str(config.BASE_DIR / ".env")).exists():
        problems.append("no .env found — the Groq key lives there")
    for problem in problems:
        print(f"error: {problem}", file=sys.stderr)
    return not problems


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("question", nargs="?", help="the question to ask")
    parser.add_argument("--sources", action="store_true",
                        help="dump the retrieved chunks behind the answer")
    parser.add_argument("--sample", action="store_true",
                        help="write reports/sample_qa.md from SAMPLE_QUESTIONS")
    parser.add_argument("--force", action="store_true",
                        help="regenerate sample_qa.md even if it exists")
    args = parser.parse_args()

    if not args.question and not args.sample:
        parser.print_help()
        return 2

    if not _preflight():
        return 1

    if args.sample:
        out = ROOT / "reports" / "sample_qa.md"
        if out.exists() and not args.force:
            print(f"{out.relative_to(ROOT)} already exists; pass --force to regenerate")
            return 0
        print("Generating the sample Q&A. This makes real model calls.\n")
        results = []
        for index, question in enumerate(SAMPLE_QUESTIONS, 1):
            print(f"  [{index}/{len(SAMPLE_QUESTIONS)}] {question}")
            results.append(answer(question))
        config.ensure_dirs()
        out.write_text(_sample_md(results), encoding="utf-8")
        print(f"\nwrote {out.relative_to(ROOT)}")
        return 0

    print(render_answer(answer(args.question), show_sources=args.sources))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
